// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9Wy1b3THTSs75bMR8UrtAP
// Component: 1PwgvYc3re_2n
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Footer from "../../Footer"; // plasmic-import: EgP7ay0jOTkb3/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_consulting.module.css"; // plasmic-import: 9Wy1b3THTSs75bMR8UrtAP/projectcss
import sty from "./PlasmicLevel.module.css"; // plasmic-import: 1PwgvYc3re_2n/css

export const PlasmicLevel__VariantProps = new Array(
  "variations",
  "showMaxLevels",
  "rightSide",
  "basics"
);

export const PlasmicLevel__ArgProps = new Array(
  "children",
  "number",
  "title",
  "right"
);

function PlasmicLevel__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "variations",
        type: "private",
        initFunc: ($props, $state) => $props["variations"]
      },
      {
        path: "showMaxLevels",
        type: "private",
        initFunc: ($props, $state) => $props["showMaxLevels"]
      },
      {
        path: "rightSide",
        type: "private",
        initFunc: ($props, $state) => $props["rightSide"]
      },
      {
        path: "basics",
        type: "private",
        initFunc: ($props, $state) => $props["basics"]
      }
    ],

    [$props]
  );

  const $state = p.useDollarState(stateSpecs, $props);
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root,
        {
          [sty.rootvariations_footerOnly]: hasVariant(
            $state,
            "variations",
            "footerOnly"
          ),

          [sty.rootvariations_noFooter]: hasVariant(
            $state,
            "variations",
            "noFooter"
          )
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__vVkhW, {
          [sty.freeBoxvariations_noFooter__vVkhWriAip]: hasVariant(
            $state,
            "variations",
            "noFooter"
          )
        })}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__rsHbb, {
            [sty.freeBoxbasics__rsHbbyldwj]: hasVariant(
              $state,
              "basics",
              "basics"
            )
          })}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__pibro, {
              [sty.freeBoxrightSide__pibroYeMwA]: hasVariant(
                $state,
                "rightSide",
                "rightSide"
              ),

              [sty.freeBoxshowMaxLevels__pibroWgk8]: hasVariant(
                $state,
                "showMaxLevels",
                "showMaxLevels"
              ),

              [sty.freeBoxvariations_noFooter__pibroriAip]: hasVariant(
                $state,
                "variations",
                "noFooter"
              )
            })}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__qoev6, {
                [sty.freeBoxrightSide__qoev6YeMwA]: hasVariant(
                  $state,
                  "rightSide",
                  "rightSide"
                ),

                [sty.freeBoxshowMaxLevels__qoev6Wgk8]: hasVariant(
                  $state,
                  "showMaxLevels",
                  "showMaxLevels"
                )
              })}
            >
              {(hasVariant($state, "basics", "basics") ? false : true) ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ypBvj,
                    {
                      [sty.textbasics__ypBvjyldwj]: hasVariant(
                        $state,
                        "basics",
                        "basics"
                      ),

                      [sty.textshowMaxLevels__ypBvjWgk8]: hasVariant(
                        $state,
                        "showMaxLevels",
                        "showMaxLevels"
                      )
                    }
                  )}
                >
                  {"Advanced "}
                </div>
              ) : null}
              {(hasVariant($state, "variations", "footerOnly") ? false : true)
                ? p.renderPlasmicSlot({
                    defaultContents: (
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qF1D
                        )}
                      >
                        {"Level 1"}
                      </div>
                    ),

                    value: args.number,
                    className: classNames(sty.slotTargetNumber, {
                      [sty.slotTargetNumbervariations_footerOnly]: hasVariant(
                        $state,
                        "variations",
                        "footerOnly"
                      )
                    })
                  })
                : null}
              {(
                hasVariant($state, "showMaxLevels", "showMaxLevels")
                  ? true
                  : false
              ) ? (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rVcHw,
                    {
                      [sty.textshowMaxLevels__rVcHwWgk8]: hasVariant(
                        $state,
                        "showMaxLevels",
                        "showMaxLevels"
                      )
                    }
                  )}
                >
                  {" of 7"}
                </div>
              ) : null}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__d2Thy)}
            >
              {(hasVariant($state, "variations", "footerOnly") ? false : true)
                ? p.renderPlasmicSlot({
                    defaultContents: (
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__u7XBd
                        )}
                      >
                        {"Draw a box."}
                      </div>
                    ),

                    value: args.title,
                    className: classNames(sty.slotTargetTitle, {
                      [sty.slotTargetTitlevariations_footerOnly]: hasVariant(
                        $state,
                        "variations",
                        "footerOnly"
                      )
                    })
                  })
                : null}
            </p.Stack>

            {p.renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ua2Ou
                    )}
                  >
                    {
                      "Press r to enter rectangle drawing mode. Drag to try drawing the given shape."
                    }
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__gjQZb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1HypV
                      )}
                    />
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6JcB
                    )}
                  >
                    {"Tip: hold shift while dragging to draw a perfect square."}
                  </div>
                </React.Fragment>
              ),

              value: args.children
            })}
          </p.Stack>

          {(hasVariant($state, "rightSide", "rightSide") ? true : false) ? (
            <div
              className={classNames(projectcss.all, sty.freeBox__gb6Sf, {
                [sty.freeBoxrightSide__gb6SfYeMwA]: hasVariant(
                  $state,
                  "rightSide",
                  "rightSide"
                )
              })}
            >
              {p.renderPlasmicSlot({
                defaultContents: null,
                value: args.right
              })}
            </div>
          ) : null}
        </p.Stack>

        {(hasVariant($state, "variations", "noFooter") ? false : true) ? (
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer, {
              [sty.footervariations_noFooter]: hasVariant(
                $state,
                "variations",
                "noFooter"
              )
            })}
          />
        ) : null}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "footer"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLevel__ArgProps,
          internalVariantPropNames: PlasmicLevel__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicLevel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLevel";
  } else {
    func.displayName = `PlasmicLevel.${nodeName}`;
  }
  return func;
}

export const PlasmicLevel = Object.assign(
  // Top-level PlasmicLevel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicLevel
    internalVariantProps: PlasmicLevel__VariantProps,
    internalArgProps: PlasmicLevel__ArgProps
  }
);

export default PlasmicLevel;
/* prettier-ignore-end */
