// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9Wy1b3THTSs75bMR8UrtAP
// Component: zr6L8j65ktfjkC
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_consulting.module.css"; // plasmic-import: 9Wy1b3THTSs75bMR8UrtAP/projectcss
import sty from "./PlasmicForecast.module.css"; // plasmic-import: zr6L8j65ktfjkC/css

export const PlasmicForecast__VariantProps = new Array("variants");

export const PlasmicForecast__ArgProps = new Array("children");

function PlasmicForecast__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "variants",
        type: "private",
        initFunc: ($props, $state) => $props["variants"]
      }
    ],

    [$props]
  );

  const $state = p.useDollarState(stateSpecs, $props);
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root,
        { [sty.rootvariants_row]: hasVariant($state, "variants", "row") }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__oEhCm, {
          [sty.freeBoxvariants_row__oEhCm5O507]: hasVariant(
            $state,
            "variants",
            "row"
          )
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Wednesday",
          value: args.children
        })}
      </div>

      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img, {
          [sty.imgvariants_row]: hasVariant($state, "variants", "row")
        })}
        displayHeight={"64px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"none"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"64px"}
      />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__b5921, {
          [sty.freeBoxvariants_row__b59215O507]: hasVariant(
            $state,
            "variants",
            "row"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__pzd4,
            {
              [sty.textvariants_row__pzd45O507]: hasVariant(
                $state,
                "variants",
                "row"
              )
            }
          )}
        >
          {"68°"}
        </div>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__icLh,
            {
              [sty.textvariants_row__icLh5O507]: hasVariant(
                $state,
                "variants",
                "row"
              )
            }
          )}
        >
          {"36°"}
        </div>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__jClL, {
          [sty.freeBoxvariants_row__jClL5O507]: hasVariant(
            $state,
            "variants",
            "row"
          )
        })}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ciFi,
            {
              [sty.textvariants_row__ciFi5O507]: hasVariant(
                $state,
                "variants",
                "row"
              )
            }
          )}
        >
          {"Pollen"}
        </div>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__rihrf,
            {
              [sty.textvariants_row__rihrf5O507]: hasVariant(
                $state,
                "variants",
                "row"
              )
            }
          )}
        >
          {"35"}
        </div>
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicForecast__ArgProps,
          internalVariantPropNames: PlasmicForecast__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicForecast__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicForecast";
  } else {
    func.displayName = `PlasmicForecast.${nodeName}`;
  }
  return func;
}

export const PlasmicForecast = Object.assign(
  // Top-level PlasmicForecast renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicForecast
    internalVariantProps: PlasmicForecast__VariantProps,
    internalArgProps: PlasmicForecast__ArgProps
  }
);

export default PlasmicForecast;
/* prettier-ignore-end */
