// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9Wy1b3THTSs75bMR8UrtAP
// Component: Mkr-hQ7y8jwges
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_consulting.module.css"; // plasmic-import: 9Wy1b3THTSs75bMR8UrtAP/projectcss
import sty from "./PlasmicLandmarks.module.css"; // plasmic-import: Mkr-hQ7y8jwges/css
import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: pdyw2Y6RhxiHxv/icon

export const PlasmicLandmarks__VariantProps = new Array("variants");

export const PlasmicLandmarks__ArgProps = new Array();

function PlasmicLandmarks__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "variants",
        type: "private",
        initFunc: ($props, $state) => $props["variants"]
      }
    ],

    [$props]
  );

  const $state = p.useDollarState(stateSpecs, $props);
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root,
        { [sty.rootvariants_wide]: hasVariant($state, "variants", "wide") }
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___8A2Ib,
          {
            [sty.textvariants_wide___8A2Ib83WEk]: hasVariant(
              $state,
              "variants",
              "wide"
            )
          }
        )}
      >
        {"Landmarks"}
      </div>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__whvzB, {
          [sty.freeBoxvariants_wide__whvzB83WEk]: hasVariant(
            $state,
            "variants",
            "wide"
          )
        })}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__ogLp5, {
            [sty.freeBoxvariants_wide__ogLp583WEk]: hasVariant(
              $state,
              "variants",
              "wide"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__muA0W
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___5TLq
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(projectcss.all, sty.svg__h5I0Q)}
            role={"img"}
          />
        </div>

        <div
          className={classNames(projectcss.all, sty.freeBox__lrJm, {
            [sty.freeBoxvariants_wide__lrJm83WEk]: hasVariant(
              $state,
              "variants",
              "wide"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__nz1B,
              {
                [sty.textvariants_wide__nz1B83WEk]: hasVariant(
                  $state,
                  "variants",
                  "wide"
                )
              }
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vRe5R
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(projectcss.all, sty.svg__f64Np)}
            role={"img"}
          />
        </div>

        <div
          className={classNames(projectcss.all, sty.freeBox__hez8U, {
            [sty.freeBoxvariants_wide__hez8U83WEk]: hasVariant(
              $state,
              "variants",
              "wide"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__xlTFz
            )}
          >
            {"Mission Dolores Park"}
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__uDqiY
            )}
          >
            {"Park"}
          </div>

          <Icon12Icon
            className={classNames(projectcss.all, sty.svg__yM8Yb)}
            role={"img"}
          />
        </div>
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLandmarks__ArgProps,
          internalVariantPropNames: PlasmicLandmarks__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicLandmarks__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLandmarks";
  } else {
    func.displayName = `PlasmicLandmarks.${nodeName}`;
  }
  return func;
}

export const PlasmicLandmarks = Object.assign(
  // Top-level PlasmicLandmarks renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLandmarks
    internalVariantProps: PlasmicLandmarks__VariantProps,
    internalArgProps: PlasmicLandmarks__ArgProps
  }
);

export default PlasmicLandmarks;
/* prettier-ignore-end */
